site_name: ArianeLaunches
theme:
  name: material
  language: en
  icon:
    logo: material/rocket
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
plugins:
  - search
  
repo_url: https://github.com/kbrault/ariane-launches
repo_name: /ariane-launches
edit_uri: edit/main/docs/
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kbrault_
    - icon: fontawesome/brands/github
      link: https://github.com/kbrault/ariane-launches

# Page tree example
nav:
    - Rockets:
      - Ariane 5 : rocket/ariane5.md
    - Launches:  
      - VA256 : launch/va256.md
